version: '3.5'

services:
    backend:
        container_name: api
        environment:
            - DATABASE_URL=mongodb://mongo/giovaniaFestasDB
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./src:/usr/src/app/src
            - ./nodemon.json:/usr/src/app/nodemon.json
        command: npm run dev
    db:
        container_name: database
        image: mongo
        ports:
            - 27017:27017